/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainButton: typeof import('./src/components/ui/MainButton.vue')['default']
    MainForm: typeof import('./src/components/ui/MainForm.vue')['default']
    MainIcon: typeof import('./src/components/ui/MainIcon.vue')['default']
    MainLink: typeof import('./src/components/ui/MainLink.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    MainSearch: typeof import('./src/components/ui/inputs/MainSearch.vue')['default']
    MainTable: typeof import('./src/components/table/MainTable.vue')['default']
    MainTextarea: typeof import('./src/components/ui/inputs/MainTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
